"""The QIPS Programme Office — workstream register.

This is the single definition of what exists. The scaffold generator, the
workstream engine, the control room and the CCC agenda all read from here.
"""

DIRECTORATES = {
    "D1": ("Programme", "What the programme actually is — the intellectual product."),
    "D2": ("People", "Who delivers it and who learns on it."),
    "D3": ("Platform and Operations", "How it runs, month after month, across time zones."),
    "D4": ("Business and Governance", "What makes it viable, lawful and known."),
}

# owner_question  — the one question this workstream exists to answer
# outputs         — the artefacts it must eventually produce
# lenses          — the distinct research angles its parallel researchers take
# benchmarks      — the named comparator programmes it must compare against
# depends_on      — workstreams whose APPROVED facts it needs before it can finalise
# cohort1         — the Now / Next / Later position proposed for scoping
WORKSTREAMS = [
 dict(id="W01", d="D1", name="Needs Assessment and Market Intelligence",
   maps_to="(a) needs assessment and market analysis",
   owner_question="Who needs this programme, what capability gap does it close, and how do we know that gap is real rather than assumed?",
   outputs=["Training needs analysis with primary and secondary evidence",
            "Learner persona set with sourced characteristics",
            "Market sizing and demand signal per country",
            "Competitor and substitute map, refreshed each cohort"],
   lenses=["Published LMIC health-workforce capability gap evidence",
           "Employer-side demand: what job adverts and regulators actually ask for",
           "Learner-side demand: what this audience already buys and why",
           "Substitutes and free alternatives that could take the market"],
   benchmarks=["IHI Improvement Advisor", "ISQua Fellowship", "Africa CDC Kofi Annan Fellowship",
               "WHO/POCQI regional programmes"],
   depends_on=[], cohort1="NOW",
   note="Already partially done: the pricing evidence base contains the willingness-to-pay and comparator work."),

 dict(id="W02", d="D1", name="Curriculum and Instructional Design",
   maps_to="(b) full instructional design",
   owner_question="What must a graduate be able to do, and what sequence of learning, practice and feedback reliably gets them there in twelve months?",
   outputs=["Competency framework mapped to an external standard",
            "Month-by-month curriculum map with the artefact ladder",
            "Learning design specification per month (eLearning, live, coaching, artefact)",
            "Content production plan and authoring standards",
            "Accessibility and language standard"],
   lenses=["Competency frameworks in healthcare quality (IHI, ISQua, NAHQ, CPHQ blueprint)",
           "Instructional design evidence for long-duration blended professional programmes",
           "Workplace-based project learning and what makes capstones fail",
           "Cognitive load and completion evidence for working adults at 4 hours a week"],
   benchmarks=["IHI Improvement Advisor", "ACHS Quality Improvement Lead", "AUC Hospital Management Diploma",
               "Health Foundation GenerationQ"],
   depends_on=["W01"], calibrates_with=["W03"], cohort1="NOW",
   note="Largely built: the 12-month architecture, the artefact ladder and the monthly cycle already exist."),

 dict(id="W03", d="D1", name="Assessment, Certification and Credentialing",
   maps_to="MISSING from the original list",
   owner_question="What exactly does a graduate hold at the end, who awards it, what did they have to prove to get it, and who recognises it?",
   outputs=["Assessment strategy and blueprint with standard-setting method",
            "Capstone rubric and assessor calibration protocol",
            "Certificate specification: exact title, post-nominals, awarding entity, wording",
            "CPD and professional-body recognition applications",
            "Academic integrity, appeals and misconduct policy"],
   lenses=["Standard setting and defensible pass marks in professional certification",
           "Post-nominals and what earns the right to award them",
           "CPD accreditation routes in Nigeria, Ghana, Pakistan and internationally",
           "What comparable certificates actually say on the document"],
   benchmarks=["CPHQ (NAHQ)", "ISQua Fellowship", "ACHS QIL post-nominals", "CPSP and WACP award structures"],
   depends_on=["W02"], cohort1="NOW",
   note="BLOCKING. The council's finding was blunt: the credential is the product, and no price exists before it does."),

 dict(id="W04", d="D1", name="Practicum and Observership",
   maps_to="(c) faculty and observership design — observership half",
   owner_question="What must a participant observe, where can that be observed, and how is it made safe, lawful and assessable?",
   outputs=["Host Site Standard and scored assessment instrument",
            "Observership curriculum, instruments and portfolio specification",
            "Host site agreement pack and preceptor standard",
            "Rotation calendar and concurrency model",
            "Indemnity, scope-of-practice and safeguarding protocol"],
   lenses=["Clinical placement supervision models and supervisor time evidence",
           "Observership vs internship: liability, scope and regulatory treatment",
           "Placement capacity planning and concurrency in health systems",
           "In-country placement networks in LMIC settings"],
   benchmarks=["AUC Cairo field visits", "IHI Breakthrough Series action periods", "Australian clinical placement subsidy models"],
   depends_on=["W02", "W17"], cohort1="NOW",
   note="Host Site Standard already drafted. Blocked on the indemnity quote."),

 dict(id="W05", d="D2", name="Teaching Faculty and Faculty Development",
   maps_to="(c) faculty and observership design — faculty half",
   owner_question="Who teaches, on what basis are they qualified to, and how are they developed and quality-assured?",
   outputs=["Faculty specification and appointment criteria",
            "Faculty contract, consent and IP terms",
            "Faculty development and calibration programme",
            "Session quality standard and peer observation protocol",
            "Guest speaker policy"],
   lenses=["Faculty models in international professional programmes",
           "Honoraria and engagement norms in LMIC health education",
           "Faculty development evidence — what actually improves teaching quality",
           "Conflict of interest and commercial influence policy"],
   benchmarks=["IHI faculty model", "ISQua expert faculty", "Ghana and Nigeria postgraduate college faculty structures"],
   depends_on=["W02"], cohort1="NOW",
   note="BLOCKING for January 2027: twelve named faculty with written consent."),

 dict(id="W06", d="D2", name="Coaching Faculty and Coach Development",
   maps_to="(i) coaching faculty if different from teaching faculty",
   owner_question="Who coaches, how are they trained and supervised, and what happens when a coach stops?",
   outputs=["Coach competency framework and selection criteria",
            "Internal coach development curriculum and calibration protocol",
            "Coaching session standard, agenda and artefact review protocol",
            "Coach agreement with named alternate and continuity plan",
            "Coach supervision and quality assurance model"],
   lenses=["Improvement coaching models and what distinguishes coaching from teaching",
           "Coach-to-participant ratios and the evidence behind them",
           "Volunteer versus paid coaching: attrition evidence in professional communities",
           "Coach credentialing routes and whether to build or buy"],
   benchmarks=["IHI Improvement Coach PDP", "Health Foundation GenerationQ executive coaching",
               "NHS improvement coaching models"],
   depends_on=["W02", "W05"], cohort1="NOW",
   note="Decision taken: build capability internally. The council warns in-kind coaching is a real cost booked at zero."),

 dict(id="W07", d="D2", name="Admissions, Recruitment and Selection",
   maps_to="MISSING from the original list",
   owner_question="Who is eligible, how do we choose between applicants, and how do we fill a cohort without lowering the bar?",
   outputs=["Eligibility criteria and published entry requirements",
            "Application form, selection rubric and moderation process",
            "Sponsorship undertaking and employer release agreement",
            "Scholarship and equity policy with selection method",
            "Recruitment funnel model with conversion assumptions"],
   lenses=["Selection methods that predict completion in professional programmes",
           "Equity of access and widening participation in LMIC professional education",
           "Employer release and protected-time agreements",
           "Funnel benchmarks: enquiry to application to deposit to enrolment"],
   benchmarks=["Africa CDC Kofi Annan Fellowship selection", "Health Foundation GenerationQ selection",
               "Commonwealth Scholarship selection methodology"],
   depends_on=["W01"], calibrates_with=["W03"], cohort1="NOW",
   note="Decision taken: set on best practice. The council's missing-denominator finding lands here."),

 dict(id="W08", d="D2", name="Learner Success, Retention and Alumni",
   maps_to="(b) post-program community design, expanded",
   owner_question="How do we get people to the end, and what happens to them afterwards that makes the credential compound?",
   outputs=["Retention model with at-risk detection and intervention protocol",
            "Learner support and accessibility standard",
            "Deferral, withdrawal and re-entry policy",
            "Alumni network and community design",
            "Career pathway and progression to advanced tiers"],
   lenses=["Attrition drivers in long-duration online professional programmes",
           "Early-warning indicators and what interventions actually work",
           "Professional community and alumni network design",
           "Career outcome evidence for quality and safety credentials"],
   benchmarks=["IHI Open School community", "ISQua Fellowship alumni network",
               "Africa CDC fellowship alumni structures"],
   depends_on=["W02", "W03"], cohort1="NEXT",
   note="The council found attrition is a revenue line, not a quality metric. Retention design belongs in cohort 1 even if the alumni network does not."),

 dict(id="W09", d="D3", name="Technology and Learning Platform",
   maps_to="(h) technologies including LMS, website, electronic tools, virtual sessions",
   owner_question="What must the technology do, what do we already have, and what is the smallest stack that delivers the monthly cycle reliably in three countries?",
   outputs=["Platform requirements specification tied to the monthly cycle",
            "LMS decision and configuration standard",
            "Website and enrolment stack decision",
            "Virtual session standard: recording, captions, bandwidth floor, attendance",
            "Data architecture, integrations and reporting",
            "Low-bandwidth and mobile-first standard"],
   lenses=["LMS selection for cohort-based professional programmes",
           "Low-bandwidth and mobile delivery evidence in African and South Asian settings",
           "Virtual session tooling: recording, captioning, breakout and attendance at scale",
           "Build versus buy for enrolment, payments and CRM"],
   benchmarks=["IHI platform", "Coursera and edX delivery standards", "Moodle in LMIC health education"],
   depends_on=["W02", "W10"], cohort1="NOW",
   note="RCI already operates a Moodle estate. The Next.js landing page build script already exists."),

 dict(id="W10", d="D3", name="Cohort Operations and the Global Calendar",
   maps_to="(j) cohort management",
   owner_question="How does one month actually run, and how does a virtual programme stay genuinely open to people in time zones we did not design around?",
   outputs=["Master cohort calendar with every date named",
            "Time zone and global participation model",
            "Monthly operating runbook with roles and handoffs",
            "Attendance, participation and make-up policy",
            "Incident and escalation protocol",
            "Cohort dashboard and weekly operating rhythm"],
   lenses=["Time zone strategies in global cohort-based programmes",
           "Synchronous versus asynchronous evidence for working professionals",
           "Operating cadence and staffing ratios for cohort programmes",
           "Religious, national and academic calendar conflicts across target countries"],
   benchmarks=["IHI virtual programmes", "ISQua global education", "Global MBA cohort operations",
               "Africa CDC blended fellowship operations"],
   depends_on=["W02"], cohort1="NOW",
   note="Owns the time zone question. The monthly cycle is the product, so this workstream protects it."),

 dict(id="W11", d="D3", name="Quality Assurance and Programme Evaluation",
   maps_to="MISSING from the original list",
   owner_question="How do we know the programme is any good, and how would we find out if it were not?",
   outputs=["Programme evaluation framework with an explicit outcome model",
            "Participant, faculty and host site feedback instruments",
            "Internal quality assurance cycle and annual programme review",
            "External review and accreditation readiness path",
            "Continuous improvement log tied to the fact registry"],
   lenses=["Programme evaluation models for professional education",
           "Outcome measurement beyond satisfaction in quality improvement training",
           "External evaluation and accreditation of education programmes",
           "How comparable programmes publish their own results"],
   benchmarks=["ISQua EEA education standards", "Kirkpatrick and Moore frameworks in CPD",
               "IHI programme evaluation practice"],
   depends_on=["W02", "W03"], cohort1="NOW",
   note="A quality programme that is not itself quality-assured is a credibility problem, not an oversight."),

 dict(id="W12", d="D3", name="Data, Outcomes and Research Assets",
   maps_to="MISSING from the original list",
   owner_question="What data does this programme generate, who owns it, and what is it worth beyond the programme?",
   outputs=["Data asset inventory including the capstone improvement dataset",
            "Consent, ownership and publication terms in the participant agreement",
            "Research and publication strategy",
            "Outcome dataset specification and baseline standard",
            "Reporting pack for partners, regulators and funders"],
   lenses=["Improvement project datasets and what makes them publishable",
           "Research ethics and consent for education-derived data in multiple jurisdictions",
           "SQUIRE 2.0 and reporting standards for improvement work",
           "How education programmes convert learner work into institutional evidence"],
   benchmarks=["IHI published collaborative results", "Health Foundation evaluation outputs",
               "Breakthrough Series published outcomes"],
   depends_on=["W03", "W17"], cohort1="NOW",
   note="The council flagged this as an unclaimed asset. Fifty improvement projects with baselines is evidence nobody else holds."),

 dict(id="W13", d="D4", name="Brand, Naming and Identity",
   maps_to="(e) branding",
   owner_question="What is this called, what does it look and sound like, and whose name is on it?",
   outputs=["Programme name and naming rationale",
            "Brand architecture: SQHN, partners, programme, credential",
            "Visual identity system and asset library",
            "Voice and messaging guide",
            "Naming and trademark clearance"],
   lenses=["Naming conventions in professional credentials and fellowships",
           "Brand architecture for consortium and partner-delivered programmes",
           "Name clearance, trademark and domain availability",
           "How names signal level, commitment and geography to an LMIC professional audience"],
   benchmarks=["ISQua Fellowship", "IHI Improvement Advisor", "Health Foundation GenerationQ",
               "ACHS Quality Improvement Lead", "NAHQ CPHQ"],
   depends_on=["W03"], cohort1="NOW",
   note="Decisions taken: SQHN lead sponsor, partners named, mixed RCI and SQHN identity for now. Name not yet recommended."),

 dict(id="W14", d="D4", name="Marketing, Demand Generation and Enrolment",
   maps_to="(f) marketing and advertising",
   owner_question="How does a qualified applicant find this, believe it, and complete an application?",
   outputs=["Positioning and messaging platform",
            "Channel plan with cost per enrolment assumptions",
            "Content and campaign calendar tied to the application window",
            "Landing page, brochure and collateral system",
            "Institutional and named-account sales motion",
            "Referral and ambassador programme"],
   lenses=["Channel evidence for professional education in Nigeria, Ghana and Pakistan",
           "Institutional selling into hospitals where the trigger is regulatory",
           "Trust signals that convert for an unproven credential",
           "Cost per enrolment benchmarks in professional education"],
   benchmarks=["MIT xPRO and Emeritus B2C funnel", "IHI marketing", "Local Nigerian professional education marketing"],
   depends_on=["W01", "W13", "W16"], cohort1="NOW",
   note="Brochure, Word master and landing-page build script already exist and are current."),

 dict(id="W15", d="D4", name="Partnerships, Affiliations and Accreditation",
   maps_to="(g) affiliation and partnerships",
   owner_question="Whose name adds credibility, what does each partner actually do, and what is written down?",
   outputs=["Partner map with role, contribution and value exchange",
            "Partner agreement: revenue share, IP, exit, signing authority",
            "Affiliation wording approved in writing by each named body",
            "Accreditation and recognition roadmap",
            "Institutional and regulator relationship plan"],
   lenses=["Partnership structures in multi-organisation education programmes",
           "What affiliation claims are defensible and what invites challenge",
           "Accreditation and recognition routes worth pursuing and their lead times",
           "Regulator relationships as a demand driver"],
   benchmarks=["ISQua EEA", "JCI and SafeCare institutional relationships", "University partnership models"],
   depends_on=[], cohort1="NOW",
   note="BLOCKING and unowned: there is no signed agreement between SQHN, RCI, QAI and TAC, so nobody can sign a host site MoU."),

 dict(id="W16", d="D4", name="Pricing, Finance and Revenue Operations",
   maps_to="(d) cost, fees",
   owner_question="What does it cost, what do we charge, how does the money actually arrive, and when does it stop needing new money?",
   outputs=["Published price ladder and payment terms",
            "Unit economics and breakeven model, kept live",
            "Payment rails, collections and instalment operations",
            "Refund, deferral and non-payment policy",
            "Budget, cash flow and financial controls",
            "Funding and underwriting strategy with concentration limits"],
   lenses=["Value-based pricing evidence from comparable programmes",
           "Ability and willingness to pay in each target market",
           "Payment rails, FX and collection realities",
           "Financing models that have worked and failed in LMIC professional education"],
   benchmarks=["ISQua income-band ladder", "IHI volume discounts", "WACP multi-currency publishing",
               "AUC local and foreign rates"],
   depends_on=["W03", "W04"], cohort1="NOW",
   note="Council recommendation issued 28 July 2026, awaiting CCC approval. Blocked on the indemnity quote."),

 dict(id="W17", d="D4", name="Governance, Legal, Risk and Data Protection",
   maps_to="MISSING from the original list",
   owner_question="Who is legally responsible for what, in which jurisdiction, and what happens when something goes wrong?",
   outputs=["Governance structure, terms of reference and decision rights",
            "Contracting entity, participant terms and consumer-facing policies",
            "Data protection compliance across Nigeria, Ghana and Pakistan",
            "Indemnity and insurance programme",
            "Risk register with owners, triggers and contingency",
            "Safeguarding, ethics and conflict of interest policy"],
   lenses=["Education provider liability and student placement law",
           "Data protection across the three named jurisdictions",
           "Professional indemnity for observational placements",
           "Governance structures for multi-organisation programmes"],
   benchmarks=["ISQua governance standards", "University placement governance",
               "Nigeria Data Protection Act, Ghana DPA, Pakistan PECA and draft PDPA"],
   depends_on=[], cohort1="NOW",
   note="BLOCKING everything: the unquoted per-learner indemnity sits here and gates the price and the observership."),
]

STATES = ["DORMANT", "SCOUTING", "RESEARCHING", "IN_COUNCIL", "VERIFYING",
          "AWAITING_CCC", "APPROVED", "BLOCKED", "DEFERRED"]

def by_id(wid):
    return next(w for w in WORKSTREAMS if w["id"] == wid)
